image: "rust:latest"

stages:
  - build
  - test
  - deploy

tests:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose


deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

build:amd64:
  stage: build
  image: rust
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/sibears_farm