image: "rust:latest"

stages:
  - test
  - deploy

tests:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose


deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production