version: '3'

services:
  sibears_farm_back:
    image: sibears_farm_back:1.0
    build:
      context: ./back/
      args:
        - DOCKER_BUILDKIT=1
    environment:
      - DATABASE_URL=postgres://postgres:sibears1cool@postgres/flags
      - ROCKET_LOG_LEVEL=normal
      - CONFIG_REPO=config.json
    ports:
      - "8777:8777"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    volumes:
      - ./config.json:/srv/config.json:ro
      - ./start_sploit.py:/srv/start_sploit.py:ro

  sibears_farm_front:
    image: sibears_farm_front:1.0
    build:
      context: ./front/
      args:
        - DOCKER_BUILDKIT=1
    ports:
      - "8776:80"

  postgres:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_PASSWORD=sibears1cool
      - POSTGRES_DB=flags
    ports:
      - "5432:5432"
  external_redis:
    image: redis:7.2-alpine
    ports:
      - "6378:6379"
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "sibears1cool" ]
    volumes:
      - ./vol/external_redis:/data

  save-swagger:
    image: busybox
    depends_on:
      - sibears_farm_back
    volumes:
      - swagger-json:/spec
    command: >
      /bin/sh -c "sleep 15 && mkdir -p /spec && wget -O /spec/swagger.json http://sibears_farm_back:8777/openapi.json"

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8780:8080
    environment:
      SWAGGER_JSON: /spec/swagger.json
    volumes:
      - swagger-json:/spec

volumes:
  swagger-json:
