version: '3'

services:
  sibears_farm_back:
    image: sibears_farm_back:1.0
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:sibears1cool@postgres/flags
      - ROCKET_LOG_LEVEL=normal
    volumes:
      - ./config.json:/srv/config.json:ro
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_PASSWORD=sibears1cool
  external_redis:
    image: redis:7.2.0-alpine
    ports:
      - "6378:6379"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "sibears1cool"]
    volumes:
      - ./vol/external_redis:/data