version: '3'

services:
  sibears_farm_front:
    image: sibears_farm_front:1.0
    build: ./front/
    ports:
      - "8776:80"
  sibears_farm_back:
    image: sibears_farm_back:1.0
    build: .
    ports:
      - "8777:8777"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:sibears1cool@postgres/flags
      - ROCKET_LOG_LEVEL=normal
    volumes:
      - ./config.json:/srv/config.json:ro
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_PASSWORD=sibears1cool
    ports:
      - "5432:5432"

  external_redis:
    image: redis:7.2-alpine
    ports:
      - "6378:6379"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "sibears1cool"]
    volumes:
      - ./vol/external_redis:/data
