#[macro_use] extern crate diesel;
#[macro_use] extern crate rocket;
#[macro_use] extern crate serde_json;
#[macro_use] extern crate diesel_enum;

// pub mod config;
// pub mod controllers;
// pub mod db;
// pub mod handlers;
// pub mod middleware;
// pub mod models;
// pub mod protocols;
// pub mod repos;
// pub mod rocket_init;
// pub mod settings;
pub mod domain;
pub mod infrastructure;
pub mod schema;
pub mod application;
pub mod presentation;