name: Rust Clippy Analysis

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'back/**'
  schedule:
    - cron: '19 9 * * 0'

jobs:
  rust-clippy-analyze:
    name: Run rust-clippy analyzing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install required cargo tools
        run: cargo install clippy-sarif sarif-fmt

      - name: Run rust-clippy
        working-directory: ./back
        run: |
          cargo clippy \
            --all-features \
            --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./back/rust-clippy-results.sarif
          wait-for-processing: true
